batch_size: 4
data: spider
eval_gen:
  max_length: 1024
  min_length: 5
  num_beams: 5
learning_rate: 0.004
model: state-spaces/mamba-1.4b
no_save: false
num_epochs: 10
peft: cfg/final/peft/mamba-1.4b/spider/add_scan.json
prec: bf16
seed: 42
