batch_size: 2
data: samsum
eval_gen:
  max_length: 1024
  min_length: 5
  num_beams: 5
learning_rate: 0.0002
model: state-spaces/mamba-1.4b
no_save: false
num_epochs: 10
peft: cfg/final/peft/mamba-1.4b/samsum/init_state.json
prec: bf16
val_data_split: test
